<?
/*********************************************************************************************************
 This code is part of the ShoutBox software (www.gerd-tentler.de/tools/shoutbox), copyright by
 Gerd Tentler. Obtain permission before selling this code or hosting it on a commercial website or
 redistributing it over the Internet or in any other medium. In all cases copyright must remain intact.
*********************************************************************************************************/

  $msg['name']      = "Jméno";
  $msg['eMail']     = "eMail";
  $msg['message']   = "Zpráva";
  $msg['smilies']   = "Smajly";
  $msg['refresh']   = "Obnovit";
  $msg['shout']     = "Pošli!";
  $msg['delete']    = "Smaž";
  $msg['confirm']   = "Chcete opravdu smazat tento vzkaz?";
  $msg['admin']     = "Admin";
  $msg['pass']      = "Heslo:";
  $msg['wrongPass'] = "Špatně zadané heslo!";
  $msg['noSpam']    = "Prosím, nespamujte!";
?>
