<?
/*********************************************************************************************************
 This code is part of the ShoutBox software (www.gerd-tentler.de/tools/shoutbox), copyright by
 Gerd Tentler. Obtain permission before selling this code or hosting it on a commercial website or
 redistributing it over the Internet or in any other medium. In all cases copyright must remain intact.
*********************************************************************************************************/

  $msg['name']      = "Ime";
  $msg['eMail']     = "eMail";
  $msg['message']   = "Sporocilo";
  $msg['smilies']   = "Smilies";
  $msg['refresh']   = "Osveli";
  $msg['shout']     = "Poalji!";
  $msg['delete']    = "Izbriai";
  $msg['confirm']   = "Izbriai za vedno";
  $msg['admin']     = "Admin";
  $msg['pass']      = "Vnesi geslo:";
  $msg['wrongPass'] = "Napacno geslo!";
  $msg['noSpam']    = "NE SPAMMAJ!!";
?>
