<?
/*********************************************************************************************************
 This code is part of the ShoutBox software (www.gerd-tentler.de/tools/shoutbox), copyright by
 Gerd Tentler. Obtain permission before selling this code or hosting it on a commercial website or
 redistributing it over the Internet or in any other medium. In all cases copyright must remain intact.
 Polish translation by marceenek.
*********************************************************************************************************/

  $msg['name']      = "Imiê";
  $msg['eMail']     = "eMail";
  $msg['message']   = "Powiedz";
  $msg['smilies']   = "Bu¼ki";
  $msg['refresh']   = "Od¶wie¿";
  $msg['shout']     = "Wy¶lij!";
  $msg['delete']    = "Usuñ";
  $msg['confirm']   = "Usuñ na zawsze?";
  $msg['admin']     = "Admin";
  $msg['pass']      = "Wpisz has³o:";
  $msg['wrongPass'] = "Z³e Has³o!";
  $msg['noSpam']    = "NIE SPAMUJ!";
?>
