<?
/*********************************************************************************************************
 This code is part of the ShoutBox software (www.gerd-tentler.de/tools/shoutbox), copyright by
 Gerd Tentler. Obtain permission before selling this code or hosting it on a commercial website or
 redistributing it over the Internet or in any other medium. In all cases copyright must remain intact.
*********************************************************************************************************/

  $msg['name']      = "Naam";
  $msg['eMail']     = "E-mail";
  $msg['message']   = "Bericht";
  $msg['smilies']   = "Emoticons";
  $msg['refresh']   = "Vernieuwen";
  $msg['shout']     = "Shout!";
  $msg['delete']    = "Verwijderen";
  $msg['confirm']   = "Weet je zeker dat je deze shout wilt verwijderen?";
  $msg['admin']     = "Admin";
  $msg['pass']      = "Wachtwoord:";
  $msg['wrongPass'] = "Fout wachtwoord!";
  $msg['noSpam']    = "NIET SPAMMEN ALSTUBLIEFT!";
?>
