<?
/*********************************************************************************************************
 This code is part of the ShoutBox software (www.gerd-tentler.de/tools/shoutbox), copyright by
 Gerd Tentler. Obtain permission before selling this code or hosting it on a commercial website or
 redistributing it over the Internet or in any other medium. In all cases copyright must remain intact.
*********************************************************************************************************/

  $msg['name']      = "ÇáÇÓã";
  $msg['eMail']     = "ÇáÈÑíÏ ÇáÅáßÊÑæäí";
  $msg['message']   = "ÇáÑÓÇáå";
  $msg['smilies']   = "ÇáÅÈÊÓÇãÇÊ";
  $msg['refresh']   = "ÊÍÏíË";
  $msg['shout']     = "ÇÑÓÇá";
  $msg['delete']    = "ÍÐÝ";
  $msg['confirm']   = "ÍÐÝ áÇ ÑÌÚå ãäå";
  $msg['admin']     = "ÇáÅÏÇÑå";
  $msg['pass']      = "ÇÏÎá ßáãÉ ÇáãÑæÑ";
  $msg['wrongPass'] = "ßáãÉ ÇáãÑæÑ ÛíÑ ÕÍíÍÉ";
  $msg['noSpam']    = "áÇ ÊÑÓá ÑÓÇÆá ãßÑÑÉ ÑÌÇÁ";
?>
