<?
/*********************************************************************************************************
 This code is part of the ShoutBox software (www.gerd-tentler.de/tools/shoutbox), copyright by
 Gerd Tentler. Obtain permission before selling this code or hosting it on a commercial website or
 redistributing it over the Internet or in any other medium. In all cases copyright must remain intact.
*********************************************************************************************************/

  $msg['name']      = "Nome";
  $msg['eMail']     = "eMail";
  $msg['message']   = "Messaggio";
  $msg['smilies']   = "Emoticons";
  $msg['refresh']   = "Aggiorna";
  $msg['shout']     = "Invia!";
  $msg['delete']    = "Cancella";
  $msg['confirm']   = "Cancella definitivamente?";
  $msg['admin']     = "Admin";
  $msg['pass']      = "Inserisci password:";
  $msg['wrongPass'] = "Password errata!";
  $msg['noSpam']    = "NIENTE SPAM PER FAVORE!";
?>
